#!/usr/bin/env python

import os
import sys

import torch
from diffusers import StableDiffusionPipeline

os.makedirs("diffusers-cache", exist_ok=True)


pipe = StableDiffusionPipeline.from_pretrained(
    # "CompVis/stable-diffusion-v1-4",
    "Mobius-labs/floral_pattern",
    cache_dir="diffusers-cache",
    # revision="fp16",
    # torch_dtype=torch.float16,
    use_auth_token=sys.argv[1],
)
